function out = lensCalcSafe(u, h, f1, f2, d, mode)

tol = 1e-9;
u_infinity_threshold = 1e15;  % Only trap genuine floating point overflow

out = struct();

out.hasInfinity  = false;
out.hasInfinity1 = false;
out.hasInfinity2 = false;
out.badCase = '';

out.v1 = NaN; out.m1 = NaN; out.h1 = NaN;
out.u2 = NaN; out.v2 = NaN; out.m2 = NaN;
out.v  = NaN; out.m  = NaN; out.hi = NaN;
out.status = '';
out.report = {};
out.diagramWarning = false;
out.diagramWarnMsg = '';
if mode == 1
    inputsToCheck = [u h f1];
else
    inputsToCheck = [u h f1 f2 d];
end

if any(isnan(inputsToCheck))
    error('lensCalc:nanInput', ...
        'One or more inputs is NaN. Please check all input fields.');
end

if any(isinf(inputsToCheck))
    error('lensCalc:infInput', ...
        'One or more inputs is Inf. Please enter finite values.');
end


% INPUT VALIDATION
% Check for zero values
if u == 0
    error('lensCalc:zeroU', ...
        'Object distance u cannot be zero.');
end

if f1 == 0
    error('lensCalc:zeroF1', ...
        'Focal length f1 cannot be zero.');
end

if mode==2 && f2==0
    error('lensCalc:zeroF2', ...
        'Focal length f2 cannot be zero.');
end

% Check for negative object distance
if u < 0
    error('lensCalc:negativeU', ...
        'Object distance u must be positive (object is on object side of lens). Given u = %.6g m', u);
end

% Check for negative lens separation in two-lens mode
if mode == 2 && d < 0
    error('lensCalc:negativeD', ...
        'Lens separation d cannot be negative. Lens 2 must be on image side of lens 1. Given d = %.6g m', d);
end

% Height validation
if h == 0
    warning('lensCalc:zeroHeight', ...
        'Object height h = 0 (point object on axis). Image will also be on axis.');
end

% Check for extreme parameter combinations that might cause numerical issues
if mode == 2 && abs(d) < abs(f1)/100
    warning('lensCalc:smallD', ...
        'Lens separation d = %.6g is very small compared to f1 = %.6g. Consider using combined lens formula.', d, f1);
end


% WARNINGS FOR EXTREME VALUEs
if abs(h) > 1e3
    warning('lensCalc:extremeHeight', ...
        'Object height |h| = %.3g is very large. Visualization may be difficult.', abs(h));
end

if abs(f1) > 1e6
    warning('lensCalc:extremeFocal', ...
        'Focal length |f| = %.3g is very large (weak lens). Results approach plane mirror.', abs(f1));
end


% SPECIAL CASE: OBJECT AT INFINITY (u >> f)
if u > u_infinity_threshold
    % When object at infinity: v = f, m → 0
    v1 = f1;
    m1 = 0;
    h1 = 0;

    out.v1 = v1;
    out.m1 = m1;
    out.h1 = h1;

    % Legacy fields
    out.v  = v1;
    out.m  = m1;
    out.hi = h1;

    out.status = 'Object at infinity (u >> f).';
    out.report = { ...
        'Single Lens', ...
        '------------------------', ...
        sprintf('Object distance, u = %.6g m (→ ∞)', u), ...
        sprintf('Object height,  h1 = %.6g m', h), ...
        sprintf('Focal Length,   f  = %.6g m', f1), ...
        sprintf('Lens type: %s', lensTypeStr(f1)), ...
        ' ', ...
        sprintf('Image Distance, v  = %.6g m (at focal point)', v1), ...
        sprintf('Image height,   h2 = %.6g m (→ 0)', h1), ...
        sprintf('Magnification,  m  = %.6g (→ 0)', m1), ...
        ' ', ...
        'Nature: Real (at focal plane)', ...
        'Orientation: Point image (m → 0)', ...
        ' ', ...
        'Note: Parallel rays from distant object focus at focal point.' ...
    };

    if mode == 2
        out.report{end+1} = ' ';
        out.report{end+1} = 'Two-lens calculation stopped (object at infinity for lens 1).';
    end
    return;
end


% LENS 1 


% Singularity when 1/f1 - 1/u = 0  => v → infinity
if abs(1/f1 - 1/u) < 1e-4
    out.hasInfinity  = true;
    out.hasInfinity1 = true;
    out.v1 = inf;
    out.m1 = inf;
    out.h1 = inf;

    % Legacy fields
    out.v  = inf;
    out.m  = inf;
    out.hi = inf;

    out.status = 'Image at infinity (lens 1).';
    out.report = { ...
        'Single Lens', ...
        '------------------------', ...
        sprintf('Object distance, u = %.6g m', u), ...
        sprintf('Object height,  h1 = %.6g m', h), ...
        sprintf('Focal Length,   f  = %.6g m', f1), ...
        sprintf('Lens type: %s', lensTypeStr(f1)), ...
        ' ', ...
        'Image Distance, v  -> Infinity', ...
        'Magnification,  m  -> Infinity', ...
        ' ', ...
        sprintf('Object is at focal point (u ≈ f = %.6g m)', f1), ...
        'Rays emerge parallel - image forms at infinity.', ...
        'Try changing u or f slightly.' ...
    };

    if mode==2
        out.report{end+1} = ' ';
        out.report{end+1} = 'Two-lens calculation stopped (lens 1 image at infinity).';
    end
    return;
end

% Lens 1 image distance and magnification
v1 = 1/(1/f1 - 1/u);

% near-infinity result — treat as infinity
if abs(v1) > 1e3
    out.hasInfinity  = true;
    out.hasInfinity1 = true;
    out.v1 = inf; out.m1 = inf; out.h1 = inf;
    out.v  = inf; out.m  = inf; out.hi = inf;
    out.status = 'Image at infinity (lens 1).';
    out.report = { ...
        'Single Lens', ...
        '------------------------', ...
        sprintf('Object distance, u = %.6g m', u), ...
        sprintf('Object height,  h1 = %.6g m', h), ...
        sprintf('Focal Length,   f  = %.6g m', f1), ...
        sprintf('Lens type: %s', lensTypeStr(f1)), ...
        ' ', ...
        'Image Distance, v  -> Infinity', ...
        'Magnification,  m  -> Infinity', ...
        ' ', ...
        sprintf('Object is near focal point (u ≈ f = %.6g m)', f1), ...
        'Rays emerge nearly parallel - image forms far away.', ...
        'Try changing u or f slightly.' ...
    };
    if mode==2
        out.report{end+1} = ' ';
        out.report{end+1} = 'Two-lens calculation stopped (lens 1 image near infinity).';
    end
    return;
end

m1 = -v1/u;
h1 = m1*h;

% Fix negative zero for image height
if h1 == 0
    h1 = 0;  % Convert -0 to 0
end

% Store for further uses
out.v1 = v1;
out.m1 = m1;
out.h1 = h1;

% Legacy fields (single lens compatibility)
out.v  = v1;
out.m  = m1;
out.hi = h1;

% SINGLE LENS 
if mode == 1
    out.status = 'Done.';
    out.report = { ...
        'Single Lens', ...
        '------------------------', ...
        sprintf('Object distance, u = %.6g m', u), ...
        sprintf('Object height,  h1 = %.6g m', h), ...
        sprintf('Focal Length,   f  = %.6g m', f1), ...
        sprintf('Lens type: %s', lensTypeStr(f1)), ...
        ' ', ...
        sprintf('Image Distance, v  = %.6g m', v1), ...
        sprintf('Image height,   h2 = %.6g m', h1), ...
        sprintf('Magnification,  m  = %.6g',   m1), ...
        ' ', ...
        sprintf('Nature: %s', natureFromV(v1)), ...
        sprintf('Orientation: %s', orientationFromM(m1)) ...
    };

    % Diagram quality check
    refScale = max(abs(u), abs(f1));
    if abs(m1) > 100
        out.diagramWarning = true;
        out.diagramWarnMsg = sprintf('|m| = %.4g — extreme magnification.\nDiagram not to scale. Output values are correct.', abs(m1));
    elseif abs(m1) < 0.001 && abs(h) > 1e-9
        out.diagramWarning = true;
        out.diagramWarnMsg = sprintf('|m| = %.4g — image nearly invisible (u >> f).\nDiagram not to scale. Output values are correct.', abs(m1));
    elseif abs(v1) > 100 * refScale
        out.diagramWarning = true;
        out.diagramWarnMsg = sprintf('Image very far (v = %.4g m).\nDiagram not to scale. Output values are correct.', v1);
    elseif abs(h) > 50
        out.diagramWarning = true;
        out.diagramWarnMsg = sprintf('Object height h = %.4g m is very large.\nDiagram scale dominated by h. Output values are correct.', h);
    elseif abs(h) > 1e-9 && abs(h) < 0.01
        out.diagramWarning = true;
        out.diagramWarnMsg = sprintf('Object height h = %.4g m is very small.\nImage arrow may be invisible on diagram. Output values are correct.', h);
    end
    return;
end

% LENS 2 

% Warning for zero lens separation
if d == 0
    warning('lensCalc:zeroSeparation', ...
        'Lens separation d = 0 (lenses in contact). Consider using combined focal length: 1/f_eff = 1/f1 + 1/f2');
end

% Object distance for lens2 (lens2 at x=d): u2 = d - v1
u2 = d - v1;
out.u2 = u2;


% u2 ≈ 0 => thin lens equation undefined
if abs(u2) < tol
    out.hasInfinity = true;     % reuse UI's setup-only path
    out.badCase = 'u2Zero';

    % keep lens 1 results
    out.v1 = v1; out.m1 = m1; out.h1 = h1;

    % mark lens2 results as undefined
    out.v2 = NaN; out.m2 = NaN;
    out.v  = NaN; out.m  = NaN; out.hi = NaN;

    out.status = 'Intermediate image at Lens 2 (u2≈0): thin-lens undefined.';
    out.report = { ...
        'Two Lenses', ...
        '------------------------', ...
        sprintf('Lens 1: v1 = %.6g m, m1 = %.6g, h2 = %.6g m', v1, m1, h1), ...
        sprintf('Lens separation, d = %.6g m', d), ...
        ' ', ...
        sprintf('Lens 2 object distance, u2 = %.6g m (≈ 0)', u2), ...
        ' ', ...
        'Degenerate case:', ...
        'Intermediate image lies exactly at lens 2 plane.', ...
        'Thin-lens equation is undefined at u2 = 0.', ...
        ' ', ...
        'Try:', ...
        '- Increase/decrease d slightly', ...
        '- Change u slightly', ...
        '- Change f1/f2 slightly' ...
    };
    return;
end

% Warning for very small u2 (numerical instability)
if abs(u2) < 100*tol && abs(u2) >= tol
    warning('lensCalc:smallU2', ...
        'Object distance for lens 2 (u2 = %.3g m) is very small. Results may be numerically unstable.', u2);
end

% Singularity for lens2: 1/f2 - 1/u2 = 0 => v2 -> infinity
if abs(1/f2 - 1/u2) < 1e-4
    out.hasInfinity  = true;
    out.hasInfinity2 = true;

    % store lens2 context
    out.v2 = inf;
    out.m2 = inf;

    % totals are infinite/undefined
    out.v  = inf;
    out.m  = inf;
    out.hi = inf;

    out.status = 'Image at infinity (lens 2).';
    out.report = [ ...
        {'Two Lenses'}, {'------------------------'}, {' '}, ...
        {'Lens 1:'}, ...
        {sprintf('Object distance, u1 = %.6g m', u)}, ...
        {sprintf('Object height,  h1 = %.6g m', h)}, ...
        {sprintf('Focal length,   f1 = %.6g m', f1)}, ...
        {sprintf('Lens 1 type: %s', lensTypeStr(f1))}, ...
        {' '}, ...
        {sprintf('Image distance, v1 = %.6g m', v1)}, ...
        {sprintf('Image height,   h2 = %.6g m', h1)}, ...
        {sprintf('Magnification,  m1 = %.6g', m1)}, ...
        {sprintf('Nature: %s', natureFromV(v1))}, ...
        {sprintf('Orientation: %s', orientationFromM(m1))}, ...
        {' '}, ...
        {sprintf('Lens separation distance, d = %.6g m', d)}, ...
        {' '}, ...
        {'Lens 2:'}, ...
        {sprintf('Object distance, u2 = %.6g m', u2)}, ...
        {sprintf('Object height,  h3 = %.6g m', h1)}, ...
        {sprintf('Focal length,   f2 = %.6g m', f2)}, ...
        {sprintf('Lens 2 type: %s', lensTypeStr(f2))}, ...
        {' '}, ...
        {'Lens 2 image distance v2 -> Infinity'}, ...
        {sprintf('Intermediate image is at focal point of lens 2 (u2 ≈ f2 = %.6g m)', f2)}, ...
        {'Try changing d, u, or f2 slightly.'} ...
    ];
    return;
end

% Lens 2 image distance and magnification (u2 can be negative)
v2 = 1/(1/f2 - 1/u2);

% near-infinity result — treat as infinity
if abs(v2) > 1e3
    out.hasInfinity  = true;
    out.hasInfinity2 = true;
    out.v2 = inf; out.m2 = inf;
    out.v  = inf; out.m  = inf; out.hi = inf;
    out.status = 'Image at infinity (lens 2).';
    out.report = [ ...
        {'Two Lenses'}, {'------------------------'}, {' '}, ...
        {'Lens 1:'}, ...
        {sprintf('Object distance, u1 = %.6g m', u)}, ...
        {sprintf('Object height,  h1 = %.6g m', h)}, ...
        {sprintf('Focal length,   f1 = %.6g m', f1)}, ...
        {sprintf('Lens 1 type: %s', lensTypeStr(f1))}, ...
        {' '}, ...
        {sprintf('Image distance, v1 = %.6g m', v1)}, ...
        {sprintf('Image height,   h2 = %.6g m', h1)}, ...
        {sprintf('Magnification,  m1 = %.6g', m1)}, ...
        {sprintf('Nature: %s', natureFromV(v1))}, ...
        {sprintf('Orientation: %s', orientationFromM(m1))}, ...
        {' '}, ...
        {sprintf('Lens separation distance, d = %.6g m', d)}, ...
        {' '}, ...
        {'Lens 2:'}, ...
        {sprintf('Object distance, u2 = %.6g m', u2)}, ...
        {sprintf('Object height,  h3 = %.6g m', h1)}, ...
        {sprintf('Focal length,   f2 = %.6g m', f2)}, ...
        {sprintf('Lens 2 type: %s', lensTypeStr(f2))}, ...
        {' '}, ...
        {'Lens 2 image distance v2 -> Infinity'}, ...
        {sprintf('Intermediate image near focal point of lens 2 (u2 ≈ f2 = %.6g m)', f2)}, ...
        {'Try changing d, u, or f2 slightly.'} ...
    ];
    return;
end

m2 = -v2/u2;

mTot = m1*m2;
h2 = mTot*h;

% Fix negative zero for image height
if h2 == 0
    h2 = 0;  % Convert -0 to 0
end

% Store lens2 + totals
out.v2 = v2;
out.m2 = m2;

out.v  = v2;
out.m  = mTot;
out.hi = h2;

out.status = 'Done.';

% Report with virtual object notation and physics explanation
virtualObjNote = '';
virtualObjExplain = {};
if u2 < 0
    virtualObjNote = ' (virtual object - image 1 beyond lens 2)';
    virtualObjExplain = { ...
        ' ', ...
        'VIRTUAL OBJECT NOTE:', ...
        'The intermediate image from lens 1 would form beyond lens 2.', ...
        'Light rays converge toward this point but are intercepted by lens 2.', ...
        'This acts as a "virtual object" for lens 2 (u2 < 0).', ...
        'The thin lens equation correctly handles this with negative u2.' ...
    };
end

out.report = [ ...
    {'Two Lenses'}, ...
    {'------------------------'}, ...
    {' '}, ...
    {'Lens 1:'}, ...
    {sprintf('Object distance, u1 = %.6g m', u)}, ...
    {sprintf('Object height,  h1 = %.6g m', h)}, ...
    {sprintf('Focal length,   f1 = %.6g m', f1)}, ...
    {sprintf('Lens 1 type: %s', lensTypeStr(f1))}, ...
    {' '}, ...
    {sprintf('Image distance, v1 = %.6g m', v1)}, ...
    {sprintf('Image height,   h2 = %.6g m', h1)}, ...
    {sprintf('Magnification,  m1 = %.6g',   m1)}, ...
    {sprintf('Nature: %s', natureFromV(v1))}, ...
    {sprintf('Orientation: %s', orientationFromM(m1))}, ...
    {' '}, ...
    {sprintf('Lens separation distance, d = %.6g m', d)}, ...
    {' '}, ...
    {'Lens 2:'}, ...
    {sprintf('Object distance, u2 = %.6g m%s', u2, virtualObjNote)}, ...
    {sprintf('Object height,  h3 = %.6g m', h1)}, ...
    {sprintf('Focal length,   f2 = %.6g m', f2)}, ...
    {sprintf('Lens 2 type: %s', lensTypeStr(f2))}, ...
    {' '}, ...
    {sprintf('Image distance, v2 = %.6g m', v2)}, ...
    {sprintf('Image height,   h4 = %.6g m', h2)}, ...
    {sprintf('Magnification,  m2 = %.6g',   m2)}, ...
    {sprintf('Nature: %s', natureFromV(v2))}, ...
    {sprintf('Orientation: %s', orientationFromM(m2))}, ...
    {' '}, ...
    {sprintf('Total magnification, m = %.6g', mTot)}, ...
    {sprintf('Final image height, ho = %.6g m', h2)}, ...
    {sprintf('Final nature: %s', natureFromV(v2))}, ...
    {sprintf('Final orientation: %s', orientationFromM(mTot))}, ...
    virtualObjExplain(:)' ...
];

% Diagram quality check
refScale = max([abs(u), abs(f1), abs(f2), 1]);
if abs(mTot) > 100
    out.diagramWarning = true;
    out.diagramWarnMsg = sprintf('|m| = %.4g — extreme magnification.\nDiagram not to scale. Output values are correct.', abs(mTot));
elseif abs(mTot) < 0.001 && abs(h) > 1e-9
    out.diagramWarning = true;
    out.diagramWarnMsg = sprintf('|m| = %.4g — final image nearly invisible.\nDiagram not to scale. Output values are correct.', abs(mTot));
elseif abs(d + v2) > 100 * refScale
    out.diagramWarning = true;
    out.diagramWarnMsg = sprintf('Final image very far (x = %.4g m).\nDiagram not to scale. Output values are correct.', d+v2);
elseif abs(m1) > 100
    out.diagramWarning = true;
    out.diagramWarnMsg = sprintf('Intermediate |m1| = %.4g — extreme.\nDiagram not to scale. Output values are correct.', abs(m1));
elseif abs(m1) < 0.001 && abs(h) > 1e-9
    out.diagramWarning = true;
    out.diagramWarnMsg = sprintf('Intermediate image nearly invisible (|m1| = %.4g).\nDiagram not to scale. Output values are correct.', abs(m1));
elseif abs(h) > 50
    out.diagramWarning = true;
    out.diagramWarnMsg = sprintf('Object height h = %.4g m is very large.\nDiagram scale dominated by h. Output values are correct.', h);
elseif abs(h) > 1e-9 && abs(h) < 0.01
    out.diagramWarning = true;
    out.diagramWarnMsg = sprintf('Object height h = %.4g m is very small.\nImage arrow may be invisible on diagram. Output values are correct.', h);
end

end

% HELPER FUNCTIONS

function s = natureFromV(v)
% Using sign convention: v>0 => real image (forms on image side)
if v > 0
    s = 'Real';
else
    s = 'Virtual';
end
end

function s = orientationFromM(m)
% m<0 inverted, m>0 upright
if m < 0
    s = 'Inverted';
else
    s = 'Upright';
end
end

function s = lensTypeStr(f)
if f > 0
    s = 'Converging (Convex)';
elseif f < 0
    s = 'Diverging (Concave)';
else
    s = 'Invalid (f = 0)';
end
end